export const STOP_REASON_INTERNAL_ERROR = new Error("internal error")
export const STOP_REASON_PROCESS_SIGINT = new Error("process sigint")
export const STOP_REASON_PROCESS_BEFORE_EXIT = new Error("process before exit")
export const STOP_REASON_PROCESS_HANGUP_OR_DEATH = new Error("process hangup or death")
export const STOP_REASON_PROCESS_DEATH = new Error("process death")
export const STOP_REASON_PROCESS_EXIT = new Error("process exit")
export const STOP_REASON_NOT_SPECIFIED = new Error("not specified")
